apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: inventory-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8762
          env:
            - name: SERVER_PORT
              value: "8762"
      serviceAccountName: inventory-service

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8762
      targetPort: 8762
      nodePort: 30002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: endpoints-reader-inventory
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoints-reader-inventory-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: inventory-service
    namespace: default
roleRef:
  kind: Role
  name: endpoints-reader-inventory
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: services-reader-inventory
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: services-reader-inventory-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: inventory-service
    namespace: default
roleRef:
  kind: Role
  name: services-reader-inventory
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-reader-inventory
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-reader-inventory-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: inventory-service
    namespace: default
roleRef:
  kind: Role
  name: pods-reader-inventory
  apiGroup: rbac.authorization.k8s.io
